### ISSUE TITLE
Argon2 error in my tests.

### ISSUE THREAD

**Issue by danbee** [riverrun/argon2_elixir#22]
I'm getting occasional errors in my test suite that seem to be coming from `argon2_elixir`. The weird thing is that once I start getting the error, it consistently appears until I change the password I'm using in my test. This is the output:

```
13:13:18.932 [error] #PID<0.6958.0> running ChessWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4001 (http)
Request: POST /session
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :binary.bin_to_list(nil)
        (argon2_elixir) lib/argon2.ex:114: Argon2.verify_pass/2
        (comeonin) lib/comeonin/base.ex:129: Comeonin.Argon2.check_pass/3
        (chess) lib/chess_web/controllers/session_controller.ex:17: ChessWeb.SessionController.create/2
        (chess) lib/chess_web/controllers/session_controller.ex:1: ChessWeb.SessionController.action/2
        (chess) lib/chess_web/controllers/session_controller.ex:1: ChessWeb.SessionController.phoenix_controller_pipeline/2
        (chess) lib/chess_web/endpoint.ex:1: ChessWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (chess) lib/chess_web/endpoint.ex:1: ChessWeb.Endpoint.plug_builder_call/2
        (chess) lib/chess_web/endpoint.ex:1: ChessWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/danbarber/Projects/Personal/chess/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

I'm seeing this on a number of tests that log in. The thing that seems to fix it is changing the password I'm using in the test, but these tests were ok before. Do password hashes get cached somewhere and somehow corrupted?

**Comment by danbee** [comment]
Sure:

```elixir
defmodule Chess.Features.SessionTest do
  use ChessWeb.FeatureCase

  import Wallaby.Query
  import Chess.Factory

  test "user cannot log in with incorrect email", %{session: session} do
    insert(:user, %{email: "link@hyrule.kingdom", password: "ilovezelda"})

    session
    |> visit("/")
    |> click(css(".header__user-nav a", text: "Log in"))
    |> fill_in(text_field("Email"), with: "link@example.com")
    |> fill_in(text_field("Password"), with: "ilovezelda")
    |> click(button("Log in"))

    assert session |> has_text?("Bad email or password")
  end
end
```

Changing the password seems to fix the error.

**Comment by danbee** [comment]
The `insert` function here looks liks this:

```elixir
  def insert(:user, params) do
    %User{
      name: "Link",
      email: "link@hyrule.com",
      password: "ilovezelda"
    }
    |> User.changeset(params)
    |> Repo.insert!
  end
```

**Comment by riverrun** [comment]
And the User.changeset creates the password hash - is that correct?

**Comment by danbee** [comment]
Here are the relevant bits from the `User` model:

```elixir
defmodule Chess.Store.User do
  ...
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @registration_attrs)
    |> validate_required(@registration_attrs)
    |> unique_validations()
    |> hash_password()
  end

  ...

  defp hash_password(changeset) do
    password = get_change(changeset, :password)
    if password do
      changeset
      |> change(Argon2.add_hash(password))
    else
      changeset
    end
  end
end
```

**Comment by riverrun** [comment]
In your test, after the call to insert(:user), could you check that the password hash is actually being set?

**Comment by danbee** [comment]
I will try that.

By the way, I pasted in the wrong test earlier. That one seems to be working fine. This one is exhibiting the error:

```elixir
  test "user can log in with correct details", %{session: session} do
    insert(:user, %{email: "link@hyrule.kingdom", password: "ilovezelda"})

    session
    |> visit("/")
    |> click(css(".header__user-nav a", text: "Log in"))
    |> fill_in(text_field("Email"), with: "link@hyrule.kingdom")
    |> fill_in(text_field("Password"), with: "ilovezelda")
    |> click(button("Log in"))

    assert session |> has_text?("You are logged in")
    assert session |> has_text?("Listing games")
    assert session |> has_text?("link@hyrule.kingdom")
  end
```

**Comment by danbee** [comment]
If cloning my repo and trying a test locally is something that would help you, I can point you at a branch and test that is currently failing for me in this way: `https://github.com/danbee/chess/tree/player-finder`

Run the test with `mix test test/features/session_test.exs:33`. It requires Chromedriver to be installed (`brew cask install chromedriver`)

**Comment by danbee** [comment]
I added a `|> IO.inspect` line after the `|> Repo.insert!` and this is what I get:

```
Compiling 2 files (.ex)
Including tags: [line: "33"]
Excluding tags: [:test]

%Chess.Store.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  email: "link@hyrule.kingdom",
  games: #Ecto.Association.NotLoaded<association :games is not loaded>,
  games_as_opponent: #Ecto.Association.NotLoaded<association :games_as_opponent is not loaded>,
  id: 15950,
  inserted_at: ~N[2018-10-08 21:16:30.316102],
  name: "Link",
  password: "ilovezelda",
  password_hash: nil,
  updated_at: ~N[2018-10-08 21:16:30.321147]
}
%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools" "font-weight:bold
%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools" "font-weight:bold
17:16:31.934 [error] #PID<0.535.0> running ChessWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4001 (http)
Request: POST /session
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :binary.bin_to_list(nil)
        (argon2_elixir) lib/argon2.ex:114: Argon2.verify_pass/2
        (comeonin) lib/comeonin/base.ex:129: Comeonin.Argon2.check_pass/3
        (chess) lib/chess_web/controllers/session_controller.ex:17: ChessWeb.SessionController.create/2
        (chess) lib/chess_web/controllers/session_controller.ex:1: ChessWeb.SessionController.action/2
        (chess) lib/chess_web/controllers/session_controller.ex:1: ChessWeb.SessionController.phoenix_controller_pipeline/2
        (chess) lib/chess_web/endpoint.ex:1: ChessWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (chess) lib/chess_web/endpoint.ex:1: ChessWeb.Endpoint.plug_builder_call/2
        (chess) lib/chess_web/endpoint.ex:1: ChessWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/danbarber/Projects/Personal/chess/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Looks like the hash is not being set.

Then I changed the password and now the hash *is* being calculated:

```
Including tags: [line: "33"]
Excluding tags: [:test]

%Chess.Store.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  email: "link@hyrule.kingdom",
  games: #Ecto.Association.NotLoaded<association :games is not loaded>,
  games_as_opponent: #Ecto.Association.NotLoaded<association :games_as_opponent is not loaded>,
  id: 15951,
  inserted_at: ~N[2018-10-08 21:17:37.349920],
  name: "Link",
  password: nil,
  password_hash: "$argon2i$v=19$m=65536,t=6,p=1$QtJQebUqwXBLAfqeiKtllA$ysIUbyccIaTs4ruTa5QoTgNdDg9Iy8Emlg1e6+XKYYs",
  updated_at: ~N[2018-10-08 21:17:37.352830]
}
```

Colour me confused!

**Comment by danbee** [comment]
I also noticed that the `password` attribute is getting cleared on the second one. Could that be relevant?

**Comment by riverrun** [comment]
In the first one, my guess is that Comeonin.Argon2.add_hash is not being called.

**Comment by riverrun** [comment]
In the `hash_password` function, see what the result of `get_change` is.

**Comment by riverrun** [comment]
So can we close this issue now?

**Comment by riverrun** [comment]
I'm glad we got that fixed - and without me having to update any code :)

**Comment by danbee** [comment]
Me too! Seriously, thanks for being my rubber duck. I really appreciate it!
