### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by LostKobrakai** [riverrun/argon2_elixir#25]
I just got this on a staging server of mine:
```
iex(connect@127.0.0.1)1> Comeonin.Argon2.add_hash("Benni7610Benni")
** (ArgumentError) Memory allocation error
    (argon2_elixir) lib/argon2/base.ex:147: Argon2.Base.handle_result/3
    (comeonin) lib/comeonin/base.ex:88: Comeonin.Argon2.add_hash/2
```

Restarting seemed to have fix the issue at least temporarily, but I'd like to know if there are things I could check to ensure this does not happen again?

**Comment by LostKobrakai** [comment]
So I've resized my droplet and it seems to indeed have been a plain "to less free memory" issue. I'll close this here for now.
