### ISSUE TITLE
Building in docker failing

### ISSUE THREAD

**Issue by kevinkirkup** [riverrun/argon2_elixir#48]
When trying to build an application with argon2, getting copy failures when creating a release:

```sh
#16 56.58 mkdir -p /app/_build/integration/lib/argon2_elixir/priv
#16 56.58 cc -g -O3 -pthread -Wall -Wno-format-truncation -I"/usr/local/lib/erlang/erts-12.0.3/include" -Iargon2/include -Iargon2/src -Ic_src -shared -fPIC -fvisibility=hidden -Wl,-soname,libargon2.so.0 argon2/src/argon2.c argon2/src/core.c argon2/src/blake2/blake2b.c argon2/src/thread.c argon2/src/encoding.c argon2/src/ref.c c_src/argon2_nif.c -o /app/_build/integration/lib/argon2_elixir/priv/argon2_nif.so
...
#16 181.3 Generated myapp app
#16 182.9 * assembling myapp-0.1.0 on MIX_ENV=integration
#16 182.9 * using config/runtime.exs to configure the release at runtime
#16 183.5 * creating _build/integration/rel/myapp/releases/0.1.0/vm.args
#16 183.5 * creating _build/integration/rel/myapp/releases/0.1.0/env.sh
#16 185.7 ** (File.CopyError) could not copy from "deps/argon2_elixir/priv/argon2_nif.so" to "/app/_build/integration/rel/myapp/lib/argon2_elixir-2.4.0/priv/argon2_nif.so": no such file or directory
#16 185.7     (elixir 1.12.2) lib/file.ex:711: File.copy!/3
#16 185.7     mix.exs:54: MyApp.MixProject.copy_native_libs/1
#16 185.7     (mix 1.12.2) lib/mix/tasks/release.ex:1047: Mix.Tasks.Release.run_steps/1
#16 185.7     (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
#16 185.7     (elixir 1.12.2) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
#16 185.7     (mix 1.12.2) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
#16 185.7     (mix 1.12.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
#16 185.7     (elixir 1.12.2) lib/code.ex:1261: Code.require_file/2
```

This was working with `2.3.0`.
Is failing with `2.4.0`

**Comment by kevinkirkup** [comment]
Looks like this is my issue, but I think it's caused by the change in the build directory introduced in `2.4.0`
